### ISSUE TITLE
Inquiry About Dataset Release Timing

### ISSUE THREAD

**Issue by Ultramarine-spec** [OpenLMLab/LongWanjuan#1]
I am very interested in the dataset you are preparing, as I believe it will be of great significance to my research work. Could you possibly provide an estimated release date for this dataset?

**Comment by KaiLv69** [comment]
Hi, sry for the late response. The dataset is available at https://opendatalab.com/OpenLMLab/LongWanjuan.

**Comment by Ultramarine-spec** [comment]
Thanks a lot for providing the link to the dataset!
