### ISSUE TITLE
Can not find the corresponding model file

### ISSUE THREAD

**Issue by JoyKing9327** [OpenLMLab/LongWanjuan#2]
Excuse me. I would like to check the effectiveness on the datasets I get by running the code in github. However,  the necessary models, such as DMR and InternLM2-7B, are unknown. Could you please give the model file or the download link. Thank you for your help.

**Comment by KaiLv69** [comment]
hi, the DMR model can be found at https://huggingface.co/KaiLv/dmr-zh and https://huggingface.co/KaiLv/dmr-en. The InternLM2-7B model is at https://huggingface.co/internlm/internlm2-7b.
